// Hand-written one-liners about every PKS postal area, from a residential
// developer's point of view: what the area is like, what the housing stock is,
// how it connects, and where new supply is coming from. Shown at the top of
// MarketAnalysisPanel as instant context for the clicked area.
//
// Keep these short (1–2 sentences), durable (no dates that expire) and honest —
// they frame the numbers below them.

export const POSTAL_INFO: Record<string, string> = {
    // ─── Helsinki ────────────────────────────────────────────
    '00100': 'Ydinkeskustan ja Etu-Töölön kivikaupunkia, jossa palvelut ja joukkoliikenne ovat maan parhaat. Uudistuotanto on harvinaista täydennys- ja ullakkorakentamista, hintataso kaupungin kärkeä.',
    '00120': 'Punavuoren design-kortteleiden tiivistä kivikaupunkia: pieniä asuntoja, vahva urbaani kysyntä. Uutta tulee lähinnä ullakko- ja käyttötarkoitusmuutoksina.',
    '00130': 'Kaartinkaupunki on edustus- ja toimistokortteleita ydinkeskustassa; asuntokanta pieni ja uudistuotanto käytännössä olematonta.',
    '00140': 'Kaivopuiston–Ullanlinnan perinteinen arvoalue meren äärellä. Kysyntä kestää suhdanteet, mutta rakennettavaa maata ei ole.',
    '00150': 'Eiran ja Punavuoren arvokortteleita sekä Hernesaari, jossa entinen telakka-alue muuttuu vaiheittain merelliseksi asuinalueeksi — harvoja paikkoja, joihin kantakaupungin eteläkärkeen syntyy uutta.',
    '00160': 'Katajanokka on jugend-kortteleiden ja merellisen kanavarannan arvoalue; uudistuotantoa vain poikkeustapauksissa.',
    '00170': 'Kruununhaka on vanhinta ja vakainta kivikaupunkia yliopiston ja Senaatintorin kupeessa — kysyntä tasaista, tarjonta niukkaa.',
    '00180': 'Kampin ja Ruoholahden tiivistä, uudempaa kantakaupunkia metron ja ratikoiden varrella; Jätkäsaaren kasvu tukee palveluita ja hintatasoa.',
    '00190': 'Suomenlinna on maailmanperintökohde — ei markkinaehtoista asuntotuotantoa.',
    '00200': 'Pohjois-Lauttasaari on merellinen saarikaupunginosa metroasemineen. Täydennysrakentaminen on vilkasta ja kysyntä vakaata sekä perheiltä että sinkuilta.',
    '00210': 'Vattuniemi on Lauttasaaren eteläkärjen entistä teollisuusaluetta, joka on muuttunut tiiviiksi asuinalueeksi — paljon 2000-luvun kantaa ja jatkuvaa täydennystä metron tuntumassa.',
    '00220': 'Jätkäsaari on yksi Helsingin suurimmista aluerakentamiskohteista: uutta tiivistä kerrostalokaupunkia ratikkayhteyksin. Tarjontaa valmistuu jatkuvasti, mikä pitää kilpailun kovana.',
    '00230': 'Pasilan postikeskuksen logistiikka- ja toimitila-aluetta — asuminen vähäistä.',
    '00240': 'Länsi-Pasila on 1980-luvun kompaktia kaupunkia radan varrella. Keski-Pasilan ja Triplan kasvu nostaa alueen saavutettavuuden arvoa.',
    '00250': 'Taka-Töölö on klassista kivikaupunkia Töölönlahden ja stadionin ympärillä — vakaa arvoalue, jossa uutta syntyy vain poikkeuksellisesti.',
    '00260': 'Keski-Töölö on töölöläistä kivikaupunkia parhaimmillaan: ratikat, Töölöntori ja vakaa kysyntä. Ei käytännössä uudistuotantoa.',
    '00270': 'Pohjois-Meilahti on vehreää 1930–50-luvun kerrostaloaluetta Seurasaarenselän tuntumassa; pieni ja arvostettu.',
    '00280': 'Ruskeasuo on ratikkayhteyksien varrella sairaala-alueen ja keskuspuiston välissä; täydennysrakentaminen on käynnistynyt vanhojen kortteleiden lomaan.',
    '00290': 'Meilahden sairaala-alue on HUSin kampusta — asuntokanta hyvin vähäinen.',
    '00300': 'Pikku Huopalahti on 1990-luvun postmodernia kaupunkirakentamista ratikan varrella; oma tunnistettava miljöö ja tasainen kysyntä.',
    '00310': 'Kivihaka on pieni metsäinen 1960-luvun kerrostaloalue keskuspuiston kyljessä.',
    '00320': 'Etelä-Haaga on kerrostalovaltainen, junan ja Raide-Jokerin palvelema alue. Tasainen kysyntä ja aktiivista täydennysrakentamista asemanseudulla.',
    '00330': 'Munkkiniemi on arvostettu ratikkakaupunginosa rantoineen ja puistokatuineen — vakaata arvoaluetta, jossa uutta tulee niukasti.',
    '00340': 'Kuusisaari–Lehtisaari on suurlähetystöjen ja väljien arvopientalojen aluetta; tarjonta erittäin ohutta.',
    '00350': 'Munkkivuori–Niemenmäki on 1950–60-luvun vehreää kerrostaloaluetta ostoskeskuksineen; kysyntä vakaata, yhteydet bussien varassa.',
    '00360': 'Pajamäki on pieni 1960-luvun alue Patterimäen ja Raide-Jokerin tuntumassa — hiljainen, mutta yhteydet paranivat ratikan myötä.',
    '00370': 'Reimarla on pientalovaltaista Länsi-Helsinkiä Pitäjänmäen palveluiden ja Raide-Jokerin äärellä.',
    '00380': 'Pitäjänmäen yritysalue muuttuu asteittain toimitiloista asumiseen. Juna ja Raide-Jokeri tekevät siitä kohtuuhintaisen uudistuotannon aluetta.',
    '00390': 'Konala on pientalojen ja tilaa vievän kaupan sekoitusta; Vihdintien pikaratikkasuunnitelmat toisivat toteutuessaan merkittävän tiivistymispotentiaalin.',
    '00400': 'Pohjois-Haaga on junan ja Raide-Jokerin risteysaluetta: 1950–70-luvun kantaa ja poikkeuksellisen vilkasta täydennysrakentamista.',
    '00410': 'Malminkartano on 1980-luvun tiivis-matalaa junavarren kaupunkia; hintataso Helsingin edullisimpia, kysyntä hintavetoista.',
    '00420': 'Kannelmäki on junavarren lähiö Kaaren kauppakeskuksen ympärillä — edullista kantaa ja tasaista täydennysrakentamista.',
    '00430': 'Kuninkaantammi on kasvava, puurakentamisestaan tunnettu uusi alue; Maununneva on rauhallista pientaloaluetta. Yhteydet bussien varassa.',
    '00440': 'Lassila on kerros- ja pientalojen sekoitusta Kannelmäen aseman ja Raide-Jokerin välissä; huomaamaton mutta hyvin saavutettava.',
    '00500': 'Sörnäinen–Harju on Kallion urbaanin kysynnän jatke: pienet asunnot liikkuvat, metro ja ratikat vieressä. Uudiskohteet harvassa ja menevät hyvin.',
    '00510': 'Alppila–Vallila on kantakaupungin reunan vanhaa kerrostalokaupunkia, jonka kysyntä on vahvistunut Pasilan kasvun myötä.',
    '00520': 'Itä- ja Keski-Pasila on Triplan ympärille kasvava torni- ja toimistoalue — Suomen vahvin joukkoliikennesolmu, jossa sekä valmistunutta että tulevaa tarjontaa on paljon.',
    '00530': 'Kallio on urbaanin pienasuntokysynnän ydinaluetta: likvidi markkina, jossa uudiskohteet ovat harvinaisia ja myyvät nopeasti.',
    '00540': 'Kalasatama–Sompasaari on aluerakentamisen lippulaiva: torneja ja umpikortteleita metroaseman ympärillä, ja rakentaminen jatkuu yhä uusille osa-alueille.',
    '00550': 'Vallila–Hermanni yhdistää puutalokortteleita ja uutta tuotantoa; ratikkayhteydet ja Kalasataman läheisyys tukevat kysyntää.',
    '00560': 'Toukola–Kumpula–Vanhakaupunki on puutaloidylliä ja kampusaluetta Vantaanjoen suulla; pienimuotoista täydennystä, vakaa kysyntä.',
    '00570': 'Kulosaari on metroradan varrella oleva saarikaupunginosa: arvopientaloja ja 1960-luvun kerrostaloja, hyvin rajallinen tarjonta.',
    '00580': 'Kalasatama–Kyläsaari kasvaa Verkkosaaren ja Kyläsaaren rantakortteleissa — uutta merellistä tuotantoa metron ulottuvilla.',
    '00590': 'Kruunuvuorenranta on uusi merellinen aluerakentamiskohde Laajasalossa; Kruunusillat-ratikka kytkee sen suoraan keskustaan ja tarjontaa valmistuu tasaisesti.',
    '00600': 'Koskelan vanha sairaala-alue muuttuu asuinkortteleiksi — merkittävä täydennysrakentamiskeskittymä ratikkayhteyksien äärellä.',
    '00610': 'Käpylä on Puu-Käpylän idyllin ja junayhteyden yhdistelmä; arvostettu, tarjonta niukkaa.',
    '00620': 'Metsälä–Etelä-Oulunkylä on pientalojen ja työpaikka-alueiden sekoitusta Tuusulanväylän varrella.',
    '00630': 'Maunula on 1950-luvun metsälähiö, jonka saavutettavuus parani Raide-Jokerin myötä; hintataso edullinen, täydennysrakentaminen käynnissä.',
    '00640': 'Oulunkylä–Patola on junan ja Raide-Jokerin risteyskohta, jossa täydennysrakentaminen on poikkeuksellisen voimakasta; perhekysyntää ja vanhaa kantaa rinnakkain.',
    '00650': 'Veräjämäki on pientalovaltaista Vantaanjoen vartta Oulunkylän aseman kupeessa.',
    '00660': 'Länsi-Pakila on kysyttyä pientaloaluetta; uudistuotanto on lähinnä yksittäisiä pien- ja rivitaloja.',
    '00670': 'Paloheinä on suosittu pientaloalue keskuspuiston ulkoilumaastojen äärellä — vakaa perhekysyntä.',
    '00680': 'Itä-Pakila on väljää pientaloaluetta Tuusulanväylän itäpuolella.',
    '00690': 'Torpparinmäki on rauhallista pientaloaluetta kaupungin pohjoisrajalla.',
    '00700': 'Malmi on junavarren aluekeskus, jonka ympärille suunnitellaan runsaasti uutta — Malmin kentän alue tuo vuosikymmenten rakentamispotentiaalin.',
    '00710': 'Pihlajamäki on suojeltua 1960-luvun lähiöarkkitehtuuria, Viikinmäki uudempaa kalliorinteiden kerrostalorakentamista.',
    '00720': 'Pukinmäki on junavarren edullista kantaa, jonka asemanseudulla on tilaa tiivistyä.',
    '00730': 'Tapanila on puutaloidylliä ja junayhteys — pienimuotoista täydennystä, oma vahva identiteetti.',
    '00740': 'Siltamäki on 1970-luvun matalaa kerrostaloaluetta Keravanjoen vieressä; edullinen ja rauhallinen.',
    '00750': 'Tapulikaupunki nojaa Puistolan asemaan: 1970–80-luvun kantaa ja asemanseudun tiivistymismahdollisuuksia.',
    '00760': 'Puistola–Heikinlaakso on pientalovaltaista koillista Helsinkiä junayhteyden ulottuvilla.',
    '00770': 'Alppikylä on uudehkoa tiivis-matalaa tuotantoa, Jakomäki peruskorjattua 1960-luvun kantaa — Helsingin edullisimpia alueita.',
    '00780': 'Tapaninvainio on pientaloja Keravanjoen laaksossa; tasainen perhekysyntä.',
    '00790': 'Viikki on yliopistokampuksen ja tiedepuiston ympärille kasvanutta 2000-luvun perheasumista; suunniteltu pikaratikka vahvistaisi yhteyksiä.',
    '00800': 'Länsi-Herttoniemi on 1950-luvun metsäkaupunkia metroaseman vieressä — täydennysrakentaminen tiivistää asemanseutua.',
    '00810': 'Herttoniemenranta on 1990–2000-luvun merellinen kerrostaloalue metron kupeessa; likvidi ja tasainen markkina.',
    '00820': 'Roihuvuori on vehreää 1950–60-luvun kantaa, jonka arvostus on noussut; kirsikkapuisto ja merenläheisyys vetävät.',
    '00830': 'Tammisalo on pieni pientalosaari — arvoaluetta ilman mainittavaa uudistuotantoa.',
    '00840': 'Yliskylä on Laajasalon keskus, jota Kruunusillat-ratikka ja ostoskeskuksen uudistus muuttavat voimakkaasti — paljon uutta ja tulevaa tarjontaa.',
    '00850': 'Jollas on merellisiä pientaloja Laajasalon kärjessä; rajallinen tarjonta.',
    '00860': 'Santahamina on varuskuntasaari — ei vapaata asuntomarkkinaa.',
    '00870': 'Gunillanmäki–Hevossalmi täydentyy Kruunuvuorenrannan kasvun imussa; pientaloja ja uutta pienkerrostalotuotantoa.',
    '00880': 'Roihupellon teollisuusalue on muuttumassa: Raide-Jokeri kulkee läpi ja asuntorakentaminen tekee tuloaan Keski-Herttoniemen kylkeen.',
    '00890': 'Östersundom on liitosalue, jonka suurkaavoitus odottaa ratkaisuja — toistaiseksi pientaloja ja maaseutumaista väljyyttä.',
    '00900': 'Puotinharju on 1960-luvun kantaa Itäkeskuksen kupeessa; edullinen, ja Itäkeskuksen kehityshankkeet tukevat näkymää.',
    '00910': 'Puotila on vehreä 1960-luvun alue metroasemineen ja venesatamineen; asemanseudun täydennys käynnissä.',
    '00920': 'Myllypuro kasvaa metron ja Metropolian kampuksen ympärillä — runsaasti 2010–20-luvun tuotantoa ja vahvaa opiskelija- ja vuokrakysyntää.',
    '00930': 'Itäkeskus on idän kaupallinen keskus, Marjaniemi sen kyljessä oleva arvopientaloalue. Itäkeskuksen suurhankkeet tuovat merkittävää tulevaa tarjontaa.',
    '00940': 'Kontula–Vesala–Kivikko on suuri 1960–70-luvun lähiökokonaisuus metroasemineen — Helsingin edullisinta kerrostalokantaa, täydennysrakentaminen käynnistynyt.',
    '00950': 'Vartioharju on pientaloaluetta Itäväylän molemmin puolin; metro kohtuudella saavutettavissa.',
    '00960': 'Pohjois-Vuosaari on pientalojen ja 1990-luvun kannan sekoitusta luonnonläheisesti.',
    '00970': 'Mellunmäki on metron pääteasema: 1970–80-luvun kantaa ja asemanseudun tiivistyssuunnitelmia.',
    '00980': 'Etelä-Vuosaari on metron, Columbuksen ja meren ympärille kasvanut suuralue — jatkuvaa täydennysrakentamista ja laaja hintahaitari.',
    '00990': 'Aurinkolahti on Vuosaaren rantakortteleiden arvoalue uimarantoineen ja kanavineen.',

    // ─── Espoo ───────────────────────────────────────────────
    '02100': 'Tapiola on puutarhakaupungin arvoalue, jonka keskusta on uudistunut voimakkaasti metron myötä — vahva kysyntä ja korkea hintataso.',
    '02110': 'Otsolahti on Tapiolan merellinen naapuri venesatamineen; enimmäkseen vanhempaa arvokantaa.',
    '02120': 'Länsikorkee–Suvikumpu on Tapiolan eteläpuolista vehreää 1960–70-luvun kerrostaloaluetta.',
    '02130': 'Pohjois-Tapiola on väljää puutarhakaupunkia keskuspuiston reunalla; arvostettu ja hiljainen.',
    '02140': 'Laajalahti on pientalovaltainen alue, jonka läpi Raide-Jokeri kulkee — tiivistymispotentiaalia ratikan varrella.',
    '02150': 'Otaniemi on Aalto-yliopiston kampus ja metroasema: opiskelija-asumista ja teknologiatyöpaikkoja, vapaarahoitteinen tuotanto vähäistä.',
    '02160': 'Westend on Espoon arvokkainta rantavyöhykettä — pientaloja, joiden joukkoon uutta syntyy harvoin ja kalliilla.',
    '02170': 'Haukilahti on merellinen 1960-luvun kerrostalo- ja pientaloalue venesatamineen; vakaa arvoalue.',
    '02180': 'Mankkaa on kysytty pientalovaltainen perhealue keskellä Etelä-Espoota.',
    '02200': 'Niittykumpu muuttui metroaseman myötä tornien ja uuden tuotannon alueeksi — hyvä esimerkki asemanseudun arvonnoususta.',
    '02210': 'Olari on 1970–80-luvun tiivistä kantaa; edullisempi vaihtoehto Matinkylän palveluiden vieressä.',
    '02230': 'Matinkylä on Ison Omenan ja metroterminaalin aluekeskus — runsasta uudistuotantoa ja vahvaa kysyntää.',
    '02240': 'Friisilä on rauhallista pientaloaluetta vanhan Jorvaksentien tuntumassa.',
    '02250': 'Henttaa–Suurpelto on kasvava perheasumisen alue, jonka rakentaminen jatkuu; yhteydet bussien varassa.',
    '02260': 'Kaitaa sai metroaseman ja sen ympäristöä kaavoitetaan tiiviimmäksi — nyt vielä pientalovaltainen, tulevaisuudessa selvästi urbaanimpi.',
    '02270': 'Finnoo on Espoon suurin aluerakentamiskohde: metroasema, torneja ja merellistä asumista — tulevaa tarjontaa poikkeuksellisen paljon.',
    '02280': 'Malminmäki–Eestinlaakso on vehreää kerros- ja pientaloaluetta Finnoon kasvualueen kyljessä.',
    '02300': 'Nöykkiönpuro on pientalovaltaista Länsi-Espoota; perhekysyntä nojaa kouluihin ja väljyyteen.',
    '02320': 'Espoonlahti uudistui metron ja Lippulaivan myötä — aluekeskus, jossa uudistuotanto on vilkasta ja hintataso Etelä-Espoon maltillisimpia.',
    '02330': 'Saunalahti–Kattilalaakso on 2000–2010-luvulla rakennettu perheasumisen kasvualue meren tuntumassa.',
    '02340': 'Latokaski on 1980-luvun tiivis-matalaa ja pientaloja; rauhallinen ja edullinen.',
    '02360': 'Soukka on 1970-luvun kerrostaloaluetta, jonka metroasema on käynnistänyt täydennysrakentamisen — edullinen asemanseutu.',
    '02380': 'Suvisaaristo on saaristopientaloja ja huviloita — ei mainittavaa uudistuotantoa.',
    '02600': 'Etelä-Leppävaara on Sellon aluekeskus junan ja Raide-Jokerin risteyksessä — Espoon suurimpia ja likvideimpiä kerrostalomarkkinoita, tuotanto jatkuvaa.',
    '02610': 'Kilo on junavarren tiivistyvä alue Leppävaaran ja Keran välissä; täydennysrakentamista ja kohtuuhintaa.',
    '02620': 'Karakallio on 1960–70-luvun kantaa, jonka kylkeen Raide-Jokeri toi paremmat yhteydet; täydennyssuunnitelmia vireillä.',
    '02630': 'Nihtisilta–Kera on muutosalue: Keran vanha logistiikka-alue muuttuu junaradan varrella kokonaan uudeksi kaupunginosaksi — iso tuleva pipeline.',
    '02650': 'Pohjois-Leppävaara on kerros- ja pientalojen sekoitusta Sellon palveluiden ja hyvien yhteyksien ulottuvilla.',
    '02660': 'Lintuvaara on pientalovaltaista aluetta Helsingin rajalla; tasainen perhekysyntä.',
    '02680': 'Uusmäki on pieni asuinalue Kehä II:n ja Helsingin rajan tuntumassa.',
    '02710': 'Viherlaakso on vanhaa huvila- ja pientaloaluetta Turuntien varrella; pienimuotoista täydennystä.',
    '02720': 'Lähderanta on 1960-luvun kerrostaloja ja pientaloja vehreässä ympäristössä.',
    '02730': 'Jupperi on pientaloaluetta Pitkäjärven rannalla — vakaa perhealue.',
    '02740': 'Bemböle–Pakankylä on maaseutumaista pientaloaluetta Espoon keskuksen pohjoispuolella.',
    '02750': 'Sepänkylä–Kuurinniitty on pientalovaltaista Keski-Espoota; rauhallinen ja perhevetoinen.',
    '02760': 'Tuomarila–Suvela yhdistää juna-aseman, edullisen 1970-luvun kannan ja käynnissä olevan täydennysrakentamisen.',
    '02770': 'Espoon keskus on hallinnollinen keskus junaradan varrella: edullista kantaa ja voimakasta asemanseudun uudistamista.',
    '02780': 'Kauklahti on junavarren vanha ruukkikylä, joka kasvaa — kohtuuhintaista uudistuotantoa ja oma kylämäinen identiteetti.',
    '02810': 'Gumböle–Karhusuo on väljää pientaloasumista golfkenttineen Turunväylän tuntumassa.',
    '02820': 'Nupuri–Nuuksio on järvimaisemien pientaloja kansallispuiston naapurissa; tontit isoja, tarjonta ohutta.',
    '02860': 'Siikajärvi on vapaa-ajan asumisen ja pientalojen sekoitusta Nuuksion kupeessa.',
    '02920': 'Niipperi on Pohjois-Espoon kasvavaa pientaloaluetta lapsiperheille.',
    '02940': 'Lippajärvi–Järvenperä on järvenrantaista pientalo- ja rivitaloaluetta; vakaa kysyntä.',
    '02970': 'Kalajärvi on Pohjois-Espoon paikalliskeskus — pientaloja ja paikalliset palvelut, yhteydet autovetoisia.',
    '02980': 'Lakisto on maaseutumaista haja-asutusaluetta Espoon pohjoiskärjessä.',

    // ─── Kauniainen ──────────────────────────────────────────
    '02700': 'Kauniainen on oma pikkukaupunkinsa radan varrella: pientaloja, hyvät koulut ja korkea tulotaso. Uudistuotanto on pienimuotoista täydennystä keskustassa ja asemanseudulla.',

    // ─── Vantaa ──────────────────────────────────────────────
    '01200': 'Hakunila on 1970-luvun suuri lähiö, jonka hintataso on pääkaupunkiseudun edullisimpia; suunniteltu Vantaan ratikka nostaisi saavutettavuutta selvästi.',
    '01230': 'Vaarala on pientaloaluetta Kehä III:n ja Länsimäen välissä, ratikkalinjauksen tuntumassa.',
    '01260': 'Itä-Hakkila on rauhallista pientaloaluetta Kuninkaanmäen kyljessä.',
    '01280': 'Länsimäki on Mellunmäen metroaseman naapuri Vantaan puolella — edullista 1970-luvun kantaa kävelymatkalla metrosta.',
    '01300': 'Tikkurila on Vantaan hallinnollinen ja kaupallinen keskus: juna-asema, voimakasta tornirakentamista ja vahva vuokrakysyntä.',
    '01340': 'Leinelä on Kehäradan varteen 2010-luvulla rakennettu uusi asuinalue — junayhteys suoraan lentokentälle ja keskustaan.',
    '01350': 'Hiekkaharju on junavarren kasvavaa aluetta Tikkurilan kupeessa; täydennysrakentaminen vilkasta.',
    '01360': 'Koivukylä–Havukoski on junavarren 1970-luvun kantaa — edullista ja täydennysrakentamisen kohteena.',
    '01370': 'Jokiniemi on Tikkurilan tiedepuiston ja juna-aseman ympäristöä; uutta tuotantoa aseman tuntumaan.',
    '01380': 'Kuusikko–Hakkila on työpaikka-alueiden ja pientalojen sekoitusta Lahdenväylän varrella.',
    '01390': 'Ruskeasanta–Ilola on pientalovaltaista aluetta Tuusulanväylän itäpuolella; Ruskeasannan asemavaraus Kehäradalla.',
    '01400': 'Rekola on junavarren pientalojen ja pienkerrostalojen aluetta — kohtuuhintainen ja rauhallinen.',
    '01420': 'Päiväkumpu on pientaloaluetta Keravanjoen tuntumassa.',
    '01450': 'Korso on junavarren edullinen aluekeskus Vantaan pohjoisrajalla; asemanseudun tiivistäminen etenee.',
    '01480': 'Mikkola on 1970–80-luvun kerrostaloja ja pientaloja Korson eteläpuolella.',
    '01490': 'Nikinmäki on uudehkoa pientaloaluetta lapsiperheille Vantaan koilliskulmassa.',
    '01510': 'Kirkonkylä–Veromäki on Aviapoliksen kasvualueen reunaa lentokentän kupeessa — vanhaa kyläkeskusta ja uutta työpaikkarakentamista.',
    '01520': 'Tammisto on kaupan suuryksiköiden ja 2000-luvun asumisen sekoitusta lähellä Kehärataa.',
    '01530': 'Veromiehenkylä on Aviapoliksen ydintä: toimitila-alue muuttuu asuinkaupungiksi Kehäradan aseman ympärillä — merkittävä tuleva pipeline.',
    '01600': 'Myyrmäki on Länsi-Vantaan keskus: juna-asema, voimakasta tornituotantoa ja hyvä vuokrakysyntä — edullisempi vaihtoehto Helsingin puolelle.',
    '01610': 'Kaivoksela on 1960-luvun kantaa Kehä III:n eteläpuolella; täydennysrakentaminen käynnistynyt Myyrmäen imussa.',
    '01620': 'Martinlaakso on junavarren 1970-luvun aluetta, jossa täydennysrakentaminen on vilkasta.',
    '01630': 'Hämeenkylä on pientalovaltaista Länsi-Vantaata kaupan palveluineen.',
    '01640': 'Hämevaara on pieni pientaloalue Pähkinärinteen ja Espoon rajan välissä.',
    '01650': 'Vapaala on pientaloaluetta Myyrmäen palveluiden vieressä; vakaa perhekysyntä.',
    '01660': 'Varisto on pientalojen ja tilaa vievän kaupan aluetta Vihdintien varrella.',
    '01670': 'Vantaanlaakso on pientaloja Vantaanjoen laaksossa; vehreä ja rauhallinen.',
    '01680': 'Askisto on pientaloaluetta Hämeenlinnanväylän länsipuolella.',
    '01690': 'Ylästö on arvostettua pientaloaluetta lentokentän eteläpuolella — Vantaan kysytyimpiä perhealueita.',
    '01700': 'Kivistö on Kehäradan suuri uusi kaupunkikeskus: runsaasti 2010–20-luvun tuotantoa ja iso tuleva pipeline; kilpailu uudiskaupassa kovaa.',
    '01710': 'Pähkinärinne on 1970–80-luvun kompakti kerrostaloalue Länsi-Vantaalla.',
    '01720': 'Petikko on teollisuuden ja kaupan aluetta — asuminen vähäistä.',
    '01730': 'Vantaanpuisto on pieni 1970-luvun kerrostaloalue Vantaanjoen mutkassa.',
    '01740': 'Tuupakka on logistiikan ja teollisuuden aluetta lentokentän kupeessa — ei juuri asumista.',
    '01750': 'Keimola on Kivistön pohjoispuolista kasvavaa pientaloaluetta moottoriradan historialla.',
    '01760': 'Seutula on maaseutumaista haja-asutusta lentokentän pohjoispuolella.',
    '01770': 'Martinlaakson teollisuusalue on työpaikka-aluetta — asuntokanta hyvin pieni.',
};
